stages:
  fetch:
    cmd: poetry run python src/data/fetch_temp_data.py
    deps:
      - src/data/fetch_temp_data.py
    params:
      - fetch.base_url
      - fetch.station_url_suffix
      - fetch.output_file_path_template
      - stations
    outs:
      - data/raw/temp/
    always_changed: true

  preprocess:
    cmd: poetry run python src/data/preprocess_temp_data.py
    deps:
      - src/data/preprocess_temp_data.py
      - data/raw/temp/
    params:
      - preprocess.xml_data_tag
      - preprocess.input_file_path_template
      - preprocess.output_file_path_template
      - preprocess.filter_half_hour_stations
      - stations
    outs:
      - data/preprocessed/temp/:
          persist: true

  validation:
    cmd: |
      cd gx && poetry run python run_validation.py
    deps:
      - data/preprocessed/temp/
    outs:
      - gx/great_expectations.yml
      - gx/checkpoints
      - gx/expectations
      - gx/plugins
      - gx/run_validation.py
      - gx/data_source_config.ipynb
