stages:
  fetch:
    cmd: poetry run python src/data/fetch_temp_data.py
    deps:
      - src/data/fetch_temp_data.py
    params:
      - fetch.base_url
      - fetch.station_url_suffix
      - fetch.output_file_path_template
      - stations
    outs:
      - data/raw/temp/
    always_changed: true

  preprocess:
    cmd: poetry run python src/data/preprocess_temp_data.py
    deps:
      - src/data/preprocess_temp_data.py
      - data/raw/temp/
    params:
      - preprocess.xml_data_tag
      - preprocess.input_file_path_template
      - preprocess.output_file_path_template
      - preprocess.filter_half_hour_stations
      - preprocess.data_columns
      - stations
    outs:
      - data/preprocessed/temp/:
          persist: true

  validation:
    cmd: |
      cd static/validation/gx && poetry run python validate_data.py
    deps:
      - data/preprocessed/temp/
      - static/validation/gx/validate_data.py
    params:
      - validate.base_dir
      - validate.data_source_name
      - validate.data_asset_name
      - validate.checkpoint_name
      - validate.checkpoint_run_id
      - validate.expectation_suite_name
    outs:
      - static/validation/gx/uncommitted:
          persist: true

  test_data:
    cmd: poetry run python src/data/test_data.py
    deps:
      - data/preprocessed/temp
      - src/data/test_data.py
    params:
      - preprocess.output_file_path_template
      - test.reference_file_path_template
      - test.reports_file_path_template
      - stations
    outs:
      - data/reference/temp:
          persist: true
      - static/reports:
          persist: true

  train_model:
    cmd: poetry run python src/models/train.py
    deps:
      - src/models/model.py
      - src/models/preprocess.py
      - src/models/train.py
      - data/preprocessed/temp/
    params:
      - train.target_column
      - train.columns_to_drop
      - train.temp_scaler_name
      - train.other_scaler_name
      - train.model_path_template
      - train.model_name_template
      - train.plot_name_template
      - train.lookback
      - train.forecast_horizon
      - train.test_size
      - train.val_size
      - train.batch_size
      - train.hidden_size
      - train.num_layers
      - train.dropout
      - train.learning_rate
      - train.patience
      - train.min_delta
      - train.epochs
      - train.mlflow_uri
      - train.mlflow_experiment_name
      - train.mlflow_experiment_run_name
      - train.mlflow_registered_model_name
      - stations
    outs:
      - models/:
          persist: true
