stages:
  fetch:
    cmd: poetry run python src/data/fetch_temp_data.py
    deps:
      - src/data/fetch_temp_data.py
    params:
      - fetch.base_url
      - fetch.station_url_suffix
      - fetch.output_file_path_template
      - stations
    outs:
      - data/raw/temp/
    always_changed: true

  preprocess:
    cmd: poetry run python src/data/preprocess_temp_data.py
    deps:
      - src/data/preprocess_temp_data.py
      - data/raw/temp/
    params:
      - preprocess.xml_data_tag
      - preprocess.input_file_path_template
      - preprocess.output_file_path_template
      - preprocess.filter_half_hour_stations
      - preprocess.data_columns
      - stations
    outs:
      - data/preprocessed/temp/:
          persist: true

  validation:
    cmd: |
      cd gx && poetry run python validate_data.py
    deps:
      - data/preprocessed/temp/
      - gx/validate_data.py
    outs:
      - gx/uncommitted:
          persist: true

  test_data:
    cmd: poetry run python src/data/test_data.py
    deps:
      - data/preprocessed/temp
      - src/data/test_data.py
    params:
      - preprocess.output_file_path_template
      - test.reference_file_path_template
      - stations
    outs:
      - data/reference/temp:
          persist: true
