fetch:
  base_url: 'https://meteo.arso.gov.si/uploads/probase/www/observ/surface/text/sl/recent/'
  station_url_suffix: 'observationAms_{station}_history.xml'
  output_file_path_template: 'data/raw/temp/temp_data_{station}.xml'

preprocess:
  xml_data_tag: 'metData'
  input_file_path_template: 'data/raw/temp/temp_data_{station}.xml'
  output_file_path_template: 'data/preprocessed/temp/{station}.csv'
  data_columns:
    - Location
    - Date
    - Temperature
    - Temperature dew point
    - Temperature average in time interval
    - Temperature maximum in time interval
    - Temperature minimum in time interval
    - Humidity relative
    - Humidity relative average in time interval
    - Wind direction
    - Wind direction average in time interval
    - Wind direction maximum gust in time interval
    - Wind speed
    - Wind speed average in time interval
    - Wind speed maximum in time interval
    - Air pressure
    - Air pressure average in time interval
    - Precipitation total in time interval
    - Solar radiation
    - Solar radiation average in time interval
  filter_half_hour_stations:
    - PTUJ

validate:
  base_dir: '../data/preprocessed/temp/'
  data_source_name: 'temperature'
  data_asset_name: 'temperature_data'
  checkpoint_name: 'temperature_checkpoint'
  checkpoint_run_id: 'temperature_run'
  expectation_suite_name: 'temperature_suite'

test:
  reference_file_path_template: 'data/reference/temp/{station}.csv'
  reports_file_path_template: 'reports/{station}'

train:
  target_column: 'Temperature'
  columns_to_drop:
    - Location
    - Temperature average in time interval
    - Temperature maximum in time interval
    - Temperature minimum in time interval
    - Humidity relative average in time interval
    - Wind direction average in time interval
    - Wind direction maximum gust in time interval
    - Wind speed average in time interval
    - Wind speed maximum in time interval
    - Air pressure average in time interval
    - Solar radiation average in time interval
  temp_scaler_name: 'temp_scaler.pkl'
  other_scaler_name: 'other_scaler.pkl'
  model_path_template: 'models/{station}/'
  model_name_template: 'temperature_forecaster_{station}_{timestamp}.pt'
  plot_name_template: 'results_{station}_{timestamp}.png'
  lookback: 240
  forecast_horizon: 6
  test_size: 0.2
  val_size: 0.2
  batch_size: 32
  hidden_size: 128
  num_layers: 3
  dropout: 0.123
  learning_rate: 0.0097
  patience: 7
  min_delta: 0.001
  epochs: 75
  mlflow_uri: 'https://dagshub.com/JakobOpresnik/temperatureForecaster.mlflow/'
  mlflow_experiment_name: 'Temperature Forecasting LSTM'
  mlflow_experiment_run_name: 'train_{station}'

stations:
  - LENDAVA
  - PTUJ
  - CELJE
  - CRNOMELJ
  - BOVEC
