name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Login to Railway (via token)
        run: railway login --ci <<< "${{ secrets.RAILWAY_TOKEN }}"

      - name: Deploy service
        run: railway up --service app
