name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/temp-forecaster:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/temp-forecaster:latest

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy service with prebuilt Docker image
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login
          railway link --project d98ec47d-3883-4ba2-be46-d6c9935c2772 --service temperatureForecaster
          railway up --no-build
