name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Push Docker Image, Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy via Railway CLI
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link --service temperature-forecaster
          railway redeploy
