name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Push Docker Image, Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/temperature-forecaster:latest

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy via Railway CLI
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login
          railway link --project a38b37a0-0902-4609-ab14-34f071e580de --service temperatureForecaster
          railway up --no-build --image ${{ secrets.DOCKER_USERNAME }}/temperature-forecaster:latest
