name: Fetch data on schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch_temp:
    name: Fetch and preprocess temperature data
    runs-on: ubuntu-latest

    strategy:
      matrix:
        station: [LENDAVA, PTUJ, CELJE, CRNOMELJ, BOVEC] # list of weather stations

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run fetch script
        run: |
          poetry run python src/data/fetch_temp_data.py ${{ matrix.station }}

      - name: Run pre-process script
        run: |
          poetry run python src/data/preprocess_temp_data.py ${{ matrix.station }}

      - name: Commit data changes
        run: |
          git add data
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Updated raw temperature data for ${{ matrix.station }} on $(date --iso-8601=seconds) with GitHub Actions" || echo "No change to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
