name: Auto Insert Data to Supabase

on:
  # This example uses a manual trigger, but you could use
  # push:
  #   branches: [ main ]
  # or a schedule:
  # schedule:
  #   - cron: '0 * * * *' # Every hour
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  insert_data:
    runs-on: ubuntu-latest
    env:
      # Accessing the GitHub Secrets
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_TABLE_NAME: 'weather' # This can be hardcoded if fixed, or a secret if it varies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optional, if you need the Supabase CLI for other tasks)
      # - name: Setup Supabase CLI
      #   uses: supabase/setup-cli@v1
      #   with:
      #     version: latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your desired Python version

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Create dummy CSV for testing (remove this if you have a real CSV in your repo)
        run: |
          echo "Date,Location,Temperature" > weather_data.csv
          echo "2025-06-10 10:00:00,Šentjur,21.5" >> weather_data.csv
          echo "2025-06-10 11:00:00,Šentjur,22.0" >> weather_data.csv
          echo "2025-06-10 12:00:00,Celje,20.0" >> weather_data.csv
          echo "2025-06-10 10:00:00,Šentjur,21.5" >> weather_data.csv

      - name: Run data ingestion script
        run: poetry run python save_to_supabase.py weather_data.csv
        # Replace 'your_data_ingestion_script.py' with the actual name of your Python file
        # (e.g., ingest_weather_data.py or the file containing save_data_to_supabase)
        # And pass the CSV file path as an argument if your script expects it.
        # Example if your script doesn't take args:
        # run: python -c "from your_module import save_data_to_supabase; save_data_to_supabase('weather_data.csv')"
